package exception

import "fmt"

func tst(){

	fmt.Println("exception!")
}
